### ISSUE TITLE
(All) Task 1: Become familiar with Git

### ISSUE THREAD

**Issue by lhw-1** [Tembusu-Student-Developer-Club/technebot#3]
## Task 1: Install Git / GitHub Tools

To work on GitHub, you'll first need to become familiar with using Git. Git is a software designed to track changes in source code over time, and store information on version history. 

### Terminology

The idea behind Git is simple: A set of files that make up a project is called a **repository**, or **repo** for short. Repositories can be set up either locally (on your local machine) or remotely (on GitHub / other Git websites like BitBucket, etc.). Remote repositories are often only for viewing and referencing; any direct changes should be made on the local copy of the remote repository, and then uploaded to the remote repository. 

When copying the remote repository over to the local machine to create a local copy, the process is known as **Cloning** a repository. 

In Git terms, **Pull** means to get the source code in the remote repository to your local repository, and **Push** means to upload the changes made in your local repository to the remote repository. Developers make these changes to the repository in small batches; these batches are known as **Commits**. 

Within a repository, you can set up multiple **Branches**. You can think of it as a tree, where different changes can simultaneously occur in different branches of the same repository. These **Branches** can later be **merged** to the main / master branch one by one. 

Don't worry if the terminology is overwhelming - you'll slowly get used to it!

### How to start using Git?

There are two options for you: GitHub Desktop, or just plain Git. Since Git can be intimidating for beginners, I suggest using GitHub Desktop first.

GitHub Desktop is a GUI that simplifies the Git processes, but is easier for beginners to pick up when starting to use Git. You can install it from [here](https://desktop.github.com/), and here's a [quick tutorial on how to use GitHub Desktop](https://www.youtube.com/watch?v=77W2JSL7-r8). I recommend installing and use GitHub Desktop first, and then make the switch to using command-line Git once you are comfortable with GitHub Desktop.

If you want to challenge yourself and use Git CLI from the start, you can check out [this tutorial](https://git-scm.com/docs/gittutorial) and [this page](https://nus-cs2103-ay2122s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html). You might need to do your own research at certain points - but there's plenty of YouTube video guides!

---

### Task

Before starting work on the TechneBot repository, play around with GitHub Desktop! Try creating a remote repository on GitHub under your profile (you can name it anything - you can delete it later anyway), and then:

- Clone the repository to your local machine
- Add random txt files
- Push the changes
- Modify the txt files
- Push the changes
- Create a branch on your repository
- Modify the txt files even more on your branch
- Push the changes
- Merge the branch to the main / master

These are just the basic steps for you to get familiar with Git; feel free to play around with it as much as you'd like!

Reply to this issue with a comment once you feel comfortable enough with GitHub Desktop to start making changes to the TechneBot repo!

**Comment by yeojunjie** [comment]
Completed!
